Vagrant.configure("2") do |config|
  config.vm.define "webserver" do |vm|
    vm.vm.box = "bento/ubuntu-24.04"
    vm.vm.hostname = "webserver-01"
    vm.vm.network "public_network", type: "dhcp"
    vm.vm.synced_folder "./host_folder", "/vagrant_data"
    vm.vm.network "forwarded_port", guest: 80, host: 1234
    vm.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      sudo apt-get update -y
      sudo apt-get upgrade -y
      sudo apt-get install -y git
    SHELL
    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end
  end

  config.vm.define "private_server" do |vm|
    vm.vm.box = "bento/ubuntu-24.04"
    vm.vm.hostname = "private-server"
    vm.vm.network "private_network", ip: "192.168.56.10"
    vm.vm.synced_folder "./host_folder", "/vagrant_data"
    vm.vm.provision "shell", path: "./install_packages.sh"
    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

  config.vm.define "public_server" do |vm|
    vm.vm.box = "bento/ubuntu-24.04"
    vm.vm.hostname = "public-server"
    vm.vm.network "public_network", ip: "192.168.1.100", bridge: "TP-LINK_A04E"
    vm.vm.synced_folder "./host_folder", "/home/vagrant/vm_folder"
    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end
end