version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - web-data:/usr/share/nginx/html
    networks:
      - appnet

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appnet

  cache:
    image: redis:latest
    networks:
      - appnet

volumes:
  db-data:
  web-data:

networks:
  appnet:
